name: bolt
description: Lightning fast, strongly typed network protocol
repository: https://github.com/wolfenrain/bolt
version: 0.1.0-dev.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  binarize: ^1.3.1
  collection: ^1.16.0
  equatable: ^2.0.5
  mason_logger: ^0.2.2
  meta: ^1.8.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
