name: example
description: Bolt, a lightning fast, strongly typed network protocol
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bolt: ^0.1.0-dev.1
  bolt_udp_binding: ^0.1.0-dev.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
